In [1]:
### Theoretical Questions

## Purpose and advantages of numpy

# NumPy (Numerical Python) is a fundamental package in Python that is widely used for scientific computing and data analysis. 
#It provides efficient tools for numerical operations, enabling faster computations and better handling of large datasets compared to Python's built-in data structures.

# Purpose of NumPy:
# The primary purpose of NumPy is to provide support for:
# 1. **Efficient Multi-Dimensional Arrays**: It offers a powerful N-dimensional array object (`ndarray`), which is a fast and flexible data structure for handling large datasets.
# 2. **Mathematical Functions**: NumPy includes a wide range of mathematical and statistical functions that operate on arrays and matrices, making it easy to perform element-wise operations, matrix manipulations, linear algebra, and more.
# 3. **Integration with C/C++ and Fortran**: It allows for easy integration with C, C++, and Fortran code, enabling high-performance computations and making it popular in scientific computing.

# Advantages of NumPy:
# 1. **Efficient Memory Usage**: NumPy arrays (or `ndarray`) are more memory-efficient than Python's built-in lists. They use contiguous blocks of memory, making data storage and access more efficient.
#   - Example: A NumPy array can store elements of the same type in a compact form, unlike Python lists, which store elements in a more generic, space-inefficient way.

# 2. **Fast Computation**: NumPy is optimized for numerical operations. Element-wise operations on arrays are highly efficient because NumPy performs operations at the compiled C level rather than looping through elements in Python. This makes it much faster than using native Python loops for mathematical operations.
#   - Example: Operations on NumPy arrays are 10–100 times faster than Python lists due to vectorized computations.
   
# 3. **Vectorization and Broadcasting**:
#   - **Vectorization**: NumPy allows element-wise operations on entire arrays without needing explicit loops, thanks to vectorized operations. This greatly improves code performance and simplicity.
#   - **Broadcasting**: NumPy supports broadcasting, which allows operations on arrays of different shapes in a way that would be impossible with standard Python structures.
#   - Example: Adding a scalar to an array, or adding two arrays of different shapes, is handled automatically without needing explicit loops.

# 4. **Rich Set of Mathematical Functions**: NumPy provides a rich collection of mathematical functions such as:
#   - Linear algebra functions (`numpy.linalg`)
#   - Statistical functions (`mean`, `median`, `std`, etc.)
#   - Fourier transforms
#   - Random number generation (`numpy.random`)

# 5. **Handling Large Datasets**: NumPy efficiently handles large datasets by using arrays with a consistent data type, minimizing memory usage and allowing operations on large datasets that would be difficult or impossible using standard Python structures.
   
# 6. **Interoperability**: NumPy can interact with other libraries that rely on numerical arrays, such as SciPy, Pandas, and machine learning libraries like TensorFlow and PyTorch. This interoperability makes it essential in data science, machine learning, and scientific computing workflows.

# 7. **Matrix and Linear Algebra Support**: NumPy has powerful tools for matrix operations, including matrix multiplication, determinants, eigenvalues, and other linear algebra tasks. These operations are fundamental to scientific computing and machine learning.

# How NumPy Enhances Python's Capabilities:
# 1. **Array Manipulation**: Python's native lists are not optimized for numerical operations, especially when handling large datasets. NumPy enhances Python by providing `ndarray`, which is much faster for numerical tasks and supports multi-dimensional arrays, unlike Python lists.
   
# 2. **Vectorization and Elimination of Loops**: Python loops can be slow for large datasets, but NumPy’s vectorized operations allow you to perform complex operations on entire arrays without writing explicit loops.
#   - Example: To add two arrays in Python, you might loop through each element, but with NumPy, you can simply use `array1 + array2`, which is much faster.

# 3. **Advanced Mathematical Operations**: NumPy extends Python’s built-in capabilities with a vast array of mathematical and statistical functions, including those for linear algebra, matrix manipulations, and random number generation. These functions are optimized for performance and designed specifically for numerical computations.

In [2]:
## Comparing npmean() and npaverage()

#In NumPy, both `np.mean()` and `np.average()` are used to calculate the central tendency of an array, but there are key differences between them in terms of functionality and use cases. Here’s a comparison and a guide to when you would use one over the other:

# **1. `np.mean()`**
# - **Purpose**: The `np.mean()` function computes the arithmetic mean (average) of elements in an array.
# - **Syntax**:
  
#  np.mean(a, axis=None, dtype=None, out=None, keepdims=False)
  
#- **Default Behavior**: If no axis is specified, it computes the mean of the flattened array (i.e., all elements).
#- **No Weights**: `np.mean()` does **not** support weighted averages. It simply divides the sum of all elements by the total number of elements.
#- **Use Case**: Use `np.mean()` when you want to compute a simple average without any weighting factors.

#- **Example**:
  
#  import numpy as np
#  data = np.array([1, 2, 3, 4, 5])
#  mean_value = np.mean(data)  # Output: 3.0

# **2. `np.average()`**
# - **Purpose**: The `np.average()` function can compute the average of elements in an array but also allows for **weighted averages**.
# - **Syntax**:
  
#  np.average(a, axis=None, weights=None, returned=False)

# - **Weighted Average**: If a `weights` parameter is provided, `np.average()` computes a weighted average, where each element contributes to the average according to its weight. If no weights are provided, it behaves like `np.mean()`.
# - **Returned Parameter**: The `returned=True` parameter, if set, returns a tuple with the computed average and the sum of the weights.
# - **Use Case**: Use `np.average()` when you need to compute a **weighted average**, where different elements have different levels of importance or contribution.

# - **Example**:
  
#  import numpy as np
#  data = np.array([1, 2, 3, 4, 5])
#  weights = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
#  weighted_avg = np.average(data, weights=weights)  # Output: 3.666...
  
# **When to Use `np.mean()`**:
# - When you need to compute a simple average without taking into account the relative importance of each value.
# - When you're working with unweighted datasets.
  
# - **Example**:
  
#  data = np.array([1, 2, 3, 4, 5])
#  mean_value = np.mean(data)  # Output: 3.0

# **When to Use `np.average()`**:
#- When you want to compute a **weighted average**, where certain values should contribute more or less to the final average.
#- When you need to return both the average and the sum of weights (via the `returned` parameter).

#- **Example**:
  
#  data = np.array([1, 2, 3, 4, 5])
#  weights = np.array([1, 1, 2, 2, 4])
#  weighted_avg = np.average(data, weights=weights)  # Output: 3.9

In [3]:
## 

#In NumPy, reversing an array along different axes can be achieved using various methods, such as slicing, the `np.flip()` function, and the `np.flipud()` and `np.fliplr()` functions

# **1. Reversing a 1D NumPy Array (Single Axis)**

# For a 1D array, reversing means flipping the elements so that the first element becomes the last, and vice versa.

# **Method 1: Using Slicing**
#  You can reverse the elements of a 1D array using Python slicing `[::-1]`.

#  - **Example**:
#   import numpy as np
#   arr_1d = np.array([1, 2, 3, 4, 5])
  
#   reversed_1d = arr_1d[::-1]
#   print(reversed_1d)  # Output: [5 4 3 2 1]


# **Method 2: Using `np.flip()`**
#  `np.flip()` reverses the order of elements along the specified axis. For a 1D array, it will reverse the array.

#  - **Example**:
#   reversed_1d = np.flip(arr_1d)
#   print(reversed_1d)  # Output: [5 4 3 2 1]

# **2. Reversing a 2D NumPy Array Along Different Axes**

# For 2D arrays, reversing can be done along different axes (rows, columns, or both).

# **Method 1: Using Slicing**
#  You can reverse a 2D array by slicing it along either axis or both axes.

# - **Reversing Rows (Axis 0)**: To reverse the rows of a 2D array (flip along the vertical axis):
  
#   arr_2d = np.array([[1, 2, 3],
#                      [4, 5, 6],
#                      [7, 8, 9]])
  
#   reversed_rows = arr_2d[::-1, :]
#   print(reversed_rows)
  # Output:
  # [[7 8 9]
  #  [4 5 6]
  #  [1 2 3]]


# - **Reversing Columns (Axis 1)**: To reverse the columns of a 2D array (flip along the horizontal axis):
  
#   reversed_columns = arr_2d[:, ::-1]
#   print(reversed_columns)
  # Output:
  # [[3 2 1]
  #  [6 5 4]
  #  [9 8 7]]

# - **Reversing Both Rows and Columns**: To reverse both rows and columns:

#   reversed_both = arr_2d[::-1, ::-1]
#   print(reversed_both)
  # Output:
  # [[9 8 7]
  #  [6 5 4]
  #  [3 2 1]]

# **Method 2: Using `np.flip()`**
#  `np.flip()` can also be used to reverse a 2D array along specific axes.

# - **Reversing Rows (Axis 0)**:

#   reversed_rows = np.flip(arr_2d, axis=0)
#   print(reversed_rows)
  # Output:
  # [[7 8 9]
  #  [4 5 6]
  #  [1 2 3]]

# - **Reversing Columns (Axis 1)**:
  
#   reversed_columns = np.flip(arr_2d, axis=1)
#   print(reversed_columns)
  # Output:
  # [[3 2 1]
  #  [6 5 4]
  #  [9 8 7]]

# - **Reversing Both Axes**:

#   reversed_both = np.flip(arr_2d)
#   print(reversed_both)
  # Output:
  # [[9 8 7]
  #  [6 5 4]
  #  [3 2 1]]

# **Method 3: Using `np.flipud()` and `np.fliplr()`**
# - **`np.flipud()`**: Flips a 2D array upside down (reverses rows).
#   reversed_rows = np.flipud(arr_2d)
#   print(reversed_rows)
  # Output:
  # [[7 8 9]
  #  [4 5 6]
  #  [1 2 3]]

# - **`np.fliplr()`**: Flips a 2D array left to right (reverses columns).
#   reversed_columns = np.fliplr(arr_2d)
#   print(reversed_columns)
  # Output:
  # [[3 2 1]
  #  [6 5 4]
  #  [9 8 7]]  

In [4]:
##  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance

### In NumPy, determining the data type of elements in an array can be done using the `.dtype` attribute. This attribute tells you the specific data type of the elements stored in the array.

# **1. Determining the Data Type in a NumPy Array**

# - **Using `.dtype` Attribute**:
#   The `.dtype` attribute of a NumPy array shows the data type of its elements.

#   - **Example**:
    
#    import numpy as np
    
    # Create an array of integers
#     arr_int = np.array([1, 2, 3, 4])
#     print(arr_int.dtype)  # Output: int64 (depending on the system)
    
    # Create an array of floating-point numbers
#    arr_float = np.array([1.0, 2.0, 3.0])
#    print(arr_float.dtype)  # Output: float64
    
    # Create an array of strings
#    arr_str = np.array(["apple", "banana", "cherry"])
#    print(arr_str.dtype)  # Output: <U6 (Unicode string of max length 6)
    

# - **Using `np.dtype()`**:
#   You can explicitly specify the data type when creating an array, and you can also inspect it later using the `.dtype` attribute.

#  - **Example**:
    
#    arr = np.array([1, 2, 3], dtype=np.float32)
#    print(arr.dtype)  # Output: float32

# **2. Importance of Data Types in NumPy**

# Data types in NumPy are crucial for two main reasons: **memory management** and **performance optimization**. Here’s how they impact these aspects:

# **A. Memory Management**
# - **Efficient Memory Usage**: NumPy arrays are designed to be more memory-efficient than Python lists. This efficiency comes from the fact that arrays have a fixed, homogeneous data type (all elements have the same type), allowing NumPy to allocate memory more efficiently.
#   - **Fixed-size Elements**: Each element in a NumPy array occupies a fixed amount of memory, depending on the data type. For example, an array of `int32` uses 4 bytes per element, while an array of `float64` uses 8 bytes per element. By choosing the right data type, you can control how much memory is used.
#   - **Example**:
    
#    import numpy as np
#    arr1 = np.array([1, 2, 3], dtype=np.int32)  # Each element is 4 bytes
#    arr2 = np.array([1, 2, 3], dtype=np.float64)  # Each element is 8 bytes

#    print(arr1.nbytes)  # Output: 12 bytes (3 * 4 bytes)
#    print(arr2.nbytes)  # Output: 24 bytes (3 * 8 bytes)

# - **Impact of Large Datasets**: For large datasets, selecting an appropriate data type can significantly reduce memory consumption. If your data values don't require high precision, using smaller data types (e.g., `float32` instead of `float64`) can save substantial memory.

# **B. Performance Optimization**
# - **Faster Computation**: Operations on NumPy arrays are faster than equivalent operations on Python lists, largely because NumPy arrays are stored in contiguous blocks of memory. The data type dictates how the memory is accessed and how operations are carried out.
#  - **Smaller Data Types for Speed**: Using smaller data types like `int16` or `float32` allows computations to be performed faster because less memory is read/written during each operation, and CPU caches are used more effectively. However, this comes at the cost of precision.
#  - **Vectorized Operations**: NumPy uses vectorized operations, which means it performs element-wise computations using compiled C code. The performance of these operations depends on the data type, as the CPU can process smaller data types more quickly.

# - **Example of Performance Difference**:
#  If you use a smaller data type like `int16` instead of `int64` for an array of integers, arithmetic operations on the array can be faster, especially for large arrays.

#  import numpy as np
#  arr_large_int32 = np.ones(1000000, dtype=np.int32)
#  arr_large_int64 = np.ones(1000000, dtype=np.int64)
  
  # Timing an operation (sum) on the arrays
#  %timeit arr_large_int32.sum()  # Faster due to smaller size
#  %timeit arr_large_int64.sum()  # Slower due to larger size

# - **Trade-off Between Precision and Performance**: For tasks like scientific computing, machine learning, and data analysis, it’s important to balance precision (using larger data types like `float64`) and performance (using smaller data types like `float32` or `int16`).

# **3. Common Data Types in NumPy**
# - **Integer Types**:
#  - `int8`, `int16`, `int32`, `int64` (signed integers)
#  - `uint8`, `uint16`, `uint32`, `uint64` (unsigned integers)
  
# - **Floating-Point Types**:
#  - `float16`, `float32`, `float64` (precision increases with higher number of bits)

# - **Complex Numbers**:
#  - `complex64`, `complex128` (for working with complex numbers)

# - **Boolean Type**:
#  - `bool_` (for arrays of boolean values)

# - **String Type**:
#   - `str_`, `unicode_` (for working with text data)

In [5]:
##  Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

#  **NumPy ndarray** (N-dimensional array) is a powerful data structure that allows for efficient storage and manipulation of homogeneous elements, making it ideal for scientific computing and data analysis.
# Unlike Python lists, which can store elements of different data types, all elements in an `ndarray` must be of the same type, ensuring consistent memory usage and improved performance. 
# NumPy arrays can have multiple dimensions (1D, 2D, 3D, etc.), which allows for flexible representation of complex data structures such as matrices or higher-dimensional data. 
# These arrays are fixed in size upon creation, which is different from the dynamic nature of Python lists.
# Additionally, NumPy arrays are stored in contiguous memory blocks, which makes operations on large datasets more memory-efficient and faster. 
# One key advantage of `ndarrays` is the ability to perform vectorized operations—arithmetic and other operations are applied element-wise without the need for explicit loops, leading to faster computations. 
# Furthermore, NumPy provides extensive mathematical functions and supports broadcasting, enabling operations between arrays of different shapes. 
# In contrast, Python lists do not have built-in support for element-wise operations and require loops for similar tasks, making them less efficient for numerical tasks.
# Overall, `ndarrays` offer superior performance, especially for large-scale numerical computations, due to their memory efficiency, fixed size, and support for vectorization and broadcasting.

In [6]:
##  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

# NumPy arrays provide significant performance benefits over Python lists, particularly for large-scale numerical operations.
# These advantages stem from their design and implementation, which are optimized for numerical computations. 
# Below are the key performance benefits of using NumPy arrays compared to Python lists:

# **1. Memory Efficiency**
# - **Contiguous Memory Allocation**: NumPy arrays are stored in contiguous blocks of memory, similar to arrays in lower-level programming languages like C. 
# This compact storage leads to better memory locality, which can enhance cache performance during computations. 
# In contrast, Python lists are dynamic arrays of pointers to objects, resulting in additional overhead and less efficient memory access.
  
# - **Homogeneous Data Types**: NumPy enforces homogeneous data types, which allows it to allocate memory more efficiently.
# Python lists can store mixed types, leading to more complex memory management and increased memory usage. 
# For example, an array of integers can be stored using a single data type, optimizing space, while a list of integers and strings requires more overhead.

# **2. Performance of Mathematical Operations**
# - **Vectorization**: NumPy leverages vectorization, allowing for operations to be applied to entire arrays without the need for explicit loops.
# This is achieved through low-level optimizations and compiled C code.
# For example, adding two large arrays element-wise in NumPy can be done in a single operation, while Python lists require looping through each element, leading to significant performance degradation.

# - **Batch Operations**: NumPy is designed for batch processing, enabling efficient execution of operations on large datasets. 
# For instance, calculating the mean or sum of elements in a NumPy array is optimized to run faster than performing the same operations through iterative summation in Python lists.

# **3. Broadcasting**
# - **Broadcasting Capability**: NumPy supports broadcasting, allowing arrays of different shapes to be combined in operations.
# This feature eliminates the need for manually resizing arrays to perform element-wise operations, resulting in cleaner code and improved performance. 
# Python lists lack this capability, requiring cumbersome logic to handle shape differences, leading to slower execution times.

# **4. Built-in Mathematical Functions**
# - **Optimized Functions**: NumPy provides a comprehensive set of built-in mathematical functions, which are implemented in C and optimized for performance. 
# Functions such as `np.sum()`, `np.mean()`, and `np.dot()` are highly efficient and can significantly outperform similar operations performed on Python lists. 
# The use of optimized functions means that the performance benefits scale better with larger datasets.

# **5. Parallelism and Multi-threading**
# - **Internal Optimization**: NumPy can take advantage of parallelism and multi-threading, especially when operations are performed on large arrays. 
#  Some NumPy functions are designed to utilize multiple CPU cores, significantly speeding up computations. 
# Python lists, on the other hand, are limited by the Python Global Interpreter Lock (GIL), which can restrict performance gains from multi-threading.

# **6. Overall Execution Speed**
# - **Faster Execution**: Overall, NumPy arrays outperform Python lists in execution speed for numerical operations. 
# Benchmarks have shown that operations on NumPy arrays can be several times faster than those on Python lists, especially as the size of the data increases. 
# This speed advantage becomes more pronounced when working with very large datasets, making NumPy the preferred choice for data-intensive applications.

In [7]:
##  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

# In NumPy, the `vstack()` and `hstack()` functions are used to stack arrays vertically and horizontally, respectively. 
# They are useful for combining multiple arrays into a single array along a specified axis.
# Here’s a comparison of the two functions, along with examples demonstrating their usage and output.

# **1. `numpy.vstack()`**

# - **Purpose**: Stacks arrays vertically (row-wise).
# - **Input**: It takes a sequence of arrays and concatenates them along the first axis (axis=0), which is the vertical axis.
# - **Output**: The resulting array will have more rows and the same number of columns as the input arrays.

# **Example of `vstack()`**

# import numpy as np

# Create two 1D arrays
# arr1 = np.array([1, 2, 3])
# arr2 = np.array([4, 5, 6])

# Use vstack to stack arrays vertically
# result_vstack = np.vstack((arr1, arr2))

# print("Array 1:")
# print(arr1)
# print("\nArray 2:")
# print(arr2)
# print("\nResult of vstack:")
# print(result_vstack)

# **Output**:
# Array 1:
# [1 2 3]

# Array 2:
# [4 5 6]

# Result of vstack:
# [[1 2 3]
# [4 5 6]]

#**2. `numpy.hstack()`**

# - **Purpose**: Stacks arrays horizontally (column-wise).
# - **Input**: It takes a sequence of arrays and concatenates them along the second axis (axis=1), which is the horizontal axis.
# - **Output**: The resulting array will have the same number of rows and more columns than the input arrays.

# **Example of `hstack()`**
# import numpy as np

# Create two 1D arrays
# arr1 = np.array([1, 2, 3])
# arr2 = np.array([4, 5, 6])

# Use hstack to stack arrays horizontally
# result_hstack = np.hstack((arr1, arr2))

# print("Array 1:")
# print(arr1)
# print("\nArray 2:")
# print(arr2)
# print("\nResult of hstack:")
# print(result_hstack)

# **Output**:
# Array 1:
# [1 2 3]

# Array 2:
# [4 5 6]

# Result of hstack:
# [1 2 3 4 5 6]

# **3. Using `vstack()` and `hstack()` with 2D Arrays**

# Both functions can also be used with 2D arrays.

# **Example with 2D Arrays for `vstack()`**

# Create two 2D arrays
# arr2d_1 = np.array([[1, 2], [3, 4]])
# arr2d_2 = np.array([[5, 6], [7, 8]])

# Use vstack to stack arrays vertically
# result_vstack_2d = np.vstack((arr2d_1, arr2d_2))

# print("2D Array 1:")
# print(arr2d_1)
# print("\n2D Array 2:")
# print(arr2d_2)
# print("\nResult of vstack with 2D arrays:")
# print(result_vstack_2d)

# **Output**:

# 2D Array 1:
# [[1 2]
#  [3 4]]

# 2D Array 2:
# [[5 6]
#  [7 8]]

# Result of vstack with 2D arrays:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# **Example with 2D Arrays for `hstack()`**

# Use hstack to stack arrays horizontally
# result_hstack_2d = np.hstack((arr2d_1, arr2d_2))

# print("\nResult of hstack with 2D arrays:")
# print(result_hstack_2d)

# **Output**:

# Result of hstack with 2D arrays:
#[[1 2 5 6]
# [3 4 7 8]]

In [8]:
##  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

#In NumPy, the `fliplr()` and `flipud()` functions are used to flip arrays along specific axes.
#They are particularly useful for manipulating the orientation of arrays, and each function serves a different purpose.
#Here’s an explanation of their differences, including their effects on various array dimensions.

# **1. `numpy.fliplr()`**

#- **Purpose**: Flips an array left to right (horizontally).
#- **Effect on Dimensions**: 
#  - **1D Arrays**: `fliplr()` has no effect, as there’s no left or right to flip.
#  - **2D Arrays**: Each row of the array is reversed, which means that the first column becomes the last, the second column becomes the second-to-last, and so on.
#  - **3D Arrays and Higher**: Only the 2D slices along the last axis are flipped; the higher dimensions remain unchanged.

#**Example of `fliplr()`**

#import numpy as np

# Create a 2D array
#arr2d = np.array([[1, 2, 3],
#                  [4, 5, 6],
#                  [7, 8, 9]])

# Flip the array left to right
#flipped_lr = np.fliplr(arr2d)

#print("Original Array:")
#print(arr2d)
#print("\nFlipped Left to Right:")
#print(flipped_lr)

#**Output**:

#Original Array:
#[[1 2 3]
# [4 5 6]
# [7 8 9]]

#Flipped Left to Right:
#[[3 2 1]
# [6 5 4]
# [9 8 7]]

# **2. `numpy.flipud()`**

#- **Purpose**: Flips an array up to down (vertically).
#- **Effect on Dimensions**: 
#  - **1D Arrays**: Similar to `fliplr()`, it has no effect as there’s no up or down to flip.
#  - **2D Arrays**: Each column of the array is reversed, meaning the first row becomes the last, the second row becomes the second-to-last, and so on.
#  - **3D Arrays and Higher**: Only the 2D slices along the first axis are flipped; the higher dimensions remain unchanged.

#### **Example of `flipud()`**

# Flip the array up to down
#flipped_ud = np.flipud(arr2d)

#print("\nFlipped Up to Down:")
#print(flipped_ud)

#**Output**:

#Flipped Up to Down:
#[[7 8 9]
# [4 5 6]
# [1 2 3]]

#**3. Effects on Various Array Dimensions**

# **1D Arrays**
#- Both `fliplr()` and `flipud()` have no effect on 1D arrays since there are no dimensions to flip.

#arr1d = np.array([1, 2, 3, 4])
#print(np.fliplr(arr1d))  # Output: [1 2 3 4]
#print(np.flipud(arr1d))  # Output: [1 2 3 4]

# **2D Arrays**
#- `fliplr()` flips horizontally:
#  - Input: `[[1, 2, 3], [4, 5, 6]]`
#  - Output: `[[3, 2, 1], [6, 5, 4]]`
  
#- `flipud()` flips vertically:
#  - Input: `[[1, 2, 3], [4, 5, 6]]`
#  - Output: `[[4, 5, 6], [1, 2, 3]]`

# **3D Arrays**
#- For a 3D array, only the 2D slices along the specified axes are flipped.

#arr3d = np.array([[[1, 2], [3, 4]],
#                  [[5, 6], [7, 8]]])

# Flipping left to right
#flipped_lr_3d = np.fliplr(arr3d)
# Flipping up to down
#flipped_ud_3d = np.flipud(arr3d)

#print("\nFlipped Left to Right (3D):")
#print(flipped_lr_3d)

#print("\nFlipped Up to Down (3D):")
#print(flipped_ud_3d)

#**Output**:

#Flipped Left to Right (3D):
#[[[ 2  1]
#  [ 4  3]]

# [[ 6  5]
#  [ 8  7]]]

#Flipped Up to Down (3D):
#[[[5 6]
#  [7 8]]

# [[1 2]
#  [3 4]]]

In [9]:
##  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

# The `numpy.array_split()` method in NumPy is a versatile function that allows users to divide an array into multiple sub-arrays (or splits) along a specified axis. 
# It is particularly useful when working with large datasets, as it enables easy segmentation of data for analysis, processing, or visualization.

# **Functionality of `numpy.array_split()`**

# 1. **Basic Syntax**:
   
#   numpy.array_split(ary, indices_or_sections, axis=0)
   
#   - **`ary`**: The input array to be split.
#   - **`indices_or_sections`**: This can be an integer or a 1-D array. If it's an integer, it specifies the number of equal parts to split the array into. If it's a 1-D array, it specifies the indices at which to split the array.
#   - **`axis`**: The axis along which to split the array (default is `0`).

# 2. **Returns**: The method returns a list of sub-arrays obtained by splitting the input array.

# **Handling Uneven Splits**

# When the number of elements in the original array is not evenly divisible by the specified number of splits, `array_split()` handles the situation gracefully:

# - **Uneven Distribution**: In cases where the total number of elements cannot be evenly divided, `array_split()` will create some sub-arrays that contain one more element than others. The elements are distributed as evenly as possible among the sub-arrays.
  
# - **Example**: If you want to split an array of length 10 into 3 parts, `array_split()` will create one array with 4 elements and two arrays with 3 elements each.

# **Example Usage**

# Here are a few examples demonstrating the functionality of `array_split()`:

# **Example 1: Basic Usage**

# import numpy as np

# Create a 1D array
# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split the array into 3 parts
# splits = np.array_split(arr, 3)

# print("Original Array:")
# print(arr)
# print("\nArray after splitting into 3 parts:")
# for i, split in enumerate(splits):
#    print(f"Part {i + 1}: {split}")

# **Output**:
# Original Array:
# [ 1  2  3  4  5  6  7  8  9 10]

# Array after splitting into 3 parts:
# Part 1: [1 2 3 4]
# Part 2: [5 6 7]
# Part 3: [ 8  9 10]

# **Example 2: Uneven Splits*
# Split the array into 4 parts
# splits_uneven = np.array_split(arr, 4)

# print("\nArray after splitting into 4 parts:")
# for i, split in enumerate(splits_uneven):
#    print(f"Part {i + 1}: {split}")


# **Output**:

# Array after splitting into 4 parts:
# Part 1: [1 2 3]
# Part 2: [4 5]
# Part 3: [6 7]
# Part 4: [ 8  9 10]

In [10]:
##  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

#In NumPy, **vectorization** and **broadcasting** are key concepts that enhance the efficiency of array operations.
#These features allow for fast, efficient computations on arrays without the need for explicit loops, which can be slower and more cumbersome in Python. 
#Here’s an overview of both concepts and how they contribute to efficient array operations.

# **1. Vectorization**

#**Definition**: 
#Vectorization refers to the practice of replacing explicit loops with array expressions. In NumPy, vectorized operations are implemented at a lower level (in C) and are optimized for performance, allowing for batch processing of data.

#**Benefits**:
#- **Performance**: Vectorized operations execute much faster than traditional for-loops in Python, as they leverage optimized C and Fortran libraries under the hood.
#- **Readability**: Code that uses vectorized operations is often more concise and easier to read, allowing users to express operations in a mathematical way.
#- **Less Overhead**: By eliminating the need for explicit iteration, vectorization reduces the overhead associated with Python's loop mechanics.

#**Example of Vectorization**:

# import numpy as np

# Create two arrays
# a = np.array([1, 2, 3, 4])
# b = np.array([5, 6, 7, 8])

# Vectorized addition
# result = a + b
# print("Vectorized Addition Result:", result)

# **Output**:
# Vectorized Addition Result: [ 6  8 10 12]

# **2. Broadcasting**

# **Definition**: 
# Broadcasting is a powerful feature that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes. 
# When two arrays are involved in an operation, NumPy automatically expands the smaller array to match the shape of the larger array, enabling element-wise operations without the need to manually adjust the shapes.

# **How It Works**:
# - **Dimension Matching**: NumPy compares the shapes of the two arrays from the trailing dimensions. If the dimensions are equal or one of them is 1, broadcasting can occur.
# - **Expansion**: If one array has a dimension of size 1, it is virtually expanded to match the size of the other array along that dimension.

# **Benefits**:
# - **Ease of Use**: Broadcasting simplifies the code, allowing users to perform operations on arrays of different shapes without requiring explicit reshaping.
# - **Efficiency**: Broadcasting minimizes memory usage by avoiding the creation of large temporary arrays. Instead, it uses the original arrays, which can lead to more efficient computations.

# **Example of Broadcasting**:
# Create a 1D array and a 2D array
#a = np.array([1, 2, 3])      # Shape (3,)
#b = np.array([[10], [20], [30]])  # Shape (3, 1)

# Broadcasting addition
#result = a + b
#print("Result of Broadcasting Addition:\n", result)

#**Output**:
#Result of Broadcasting Addition:
# [[11 12 13]
# [21 22 23]
# [31 32 33]]

# In this example, the 1D array `a` is broadcast across the rows of the 2D array `b`, resulting in an array where each row of `b` has been added to `a`.

# **3. Contributions to Efficient Array Operations**

# - **Elimination of Explicit Loops**: Both vectorization and broadcasting eliminate the need for explicit loops, which can be slow in Python. This leads to significant performance improvements, especially for large datasets.
  
# - **Reduced Memory Footprint**: Broadcasting avoids unnecessary duplication of data in memory, as it performs operations on the original arrays rather than creating additional copies.
  
# - **Enhanced Computational Speed**: Vectorized operations and broadcasting can be implemented using low-level optimized libraries (like BLAS and LAPACK), which execute operations much faster than Python-level loops.
  
# - **Simplified Code**: These features allow for cleaner, more readable code, as users can express their intentions more directly without cumbersome loops or conditionals.

In [11]:
### PRACTICAL QUESTIONS

## Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

print("Original Array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T

print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[ 71  59  72]
 [ 74  77  49]
 [ 13  77 100]]

Transposed Array:
[[ 71  74  13]
 [ 59  77  77]
 [ 72  49 100]]


In [12]:
##  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # This creates an array with elements [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

print("Original 1D Array:")
print(array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:")
print(array_5x2)

Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
## Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the 4x4 array (padding of 1 on all sides)
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 Array with Zero Border:")
print(array_6x6)

Original 4x4 Array:
[[0.65034448 0.59138555 0.73714443 0.33359056]
 [0.52920411 0.88918221 0.27787934 0.84616436]
 [0.50242498 0.44154811 0.98550117 0.51734025]
 [0.20966068 0.71510052 0.99599657 0.94648761]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.65034448 0.59138555 0.73714443 0.33359056 0.        ]
 [0.         0.52920411 0.88918221 0.27787934 0.84616436 0.        ]
 [0.         0.50242498 0.44154811 0.98550117 0.51734025 0.        ]
 [0.         0.20966068 0.71510052 0.99599657 0.94648761 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [14]:
##  Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [15]:
##  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element

import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

print("Original Array:")
print(array)

# Apply uppercase transformation
uppercase_array = np.char.upper(array)
print("\nUppercase Array:")
print(uppercase_array)

# Apply lowercase transformation
lowercase_array = np.char.lower(array)
print("\nLowercase Array:")
print(lowercase_array)

# Apply title case transformation
titlecase_array = np.char.title(array)
print("\nTitle Case Array:")
print(titlecase_array)

Original Array:
['python' 'numpy' 'pandas']

Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
['python' 'numpy' 'pandas']

Title Case Array:
['Python' 'Numpy' 'Pandas']


In [16]:
## Generate a NumPy array of words. Insert a space between each character of every word in the array

import numpy as np

# Create a NumPy array of words
arr = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
arr_spaced = np.char.join(' ', arr)

print("Array with spaces between each character:")
print(arr_spaced)

Array with spaces between each character:
['p y t h o n' 'n u m p y' 'p a n d a s']


In [17]:
##  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[6, 5, 4], [3, 2, 1]])

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

# Element-wise addition
addition = array1 + array2
print("\nElement-wise Addition:")
print(addition)

# Element-wise subtraction
subtraction = array1 - array2
print("\nElement-wise Subtraction:")
print(subtraction)

# Element-wise multiplication
multiplication = array1 * array2
print("\nElement-wise Multiplication:")
print(multiplication)

# Element-wise division
division = array1 / array2
print("\nElement-wise Division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[6 5 4]
 [3 2 1]]

Element-wise Addition:
[[7 7 7]
 [7 7 7]]

Element-wise Subtraction:
[[-5 -3 -1]
 [ 1  3  5]]

Element-wise Multiplication:
[[ 6 10 12]
 [12 10  6]]

Element-wise Division:
[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


In [18]:
## Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [19]:
##  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

print("Random Array of 100 integers:")
print(random_integers)

# Find and display all prime numbers in the array
primes = [num for num in random_integers if is_prime(num)]

print("\nPrime Numbers in the Array:")
print(primes)

Random Array of 100 integers:
[225  40 372 260 973 831 350 696 810 466 895 660 994 199 238 711 614 163
 618 382   5 244  43 926 408 559 304 964 187 185 683 475 376  15 694 879
 574 236 777 270 986 394 437 157 207 280 662 375 312 771 819 145 262 110
 260 265 915 577 655 122 684 476 192 901  71 261 571 733 892 608 139 212
 637 246 297 839 810 676 502 481 705 440 961 782 537  57 996   1 698 599
 752  40 559 837 976 916 158 102 254  37]

Prime Numbers in the Array:
[199, 163, 5, 43, 683, 157, 577, 71, 571, 733, 139, 839, 599, 37]


In [20]:
##  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np

# Create a NumPy array representing daily temperatures for a 30-day month
daily_temperatures = np.random.randint(20, 40, size=30)  # Temperatures between 20 and 40 degrees

print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Reshape the array into 4 weeks (assuming 7 days in each week)
weeks = daily_temperatures[:28].reshape(4, 7)  # Only consider the first 28 days for complete weeks

# Calculate the weekly averages
weekly_averages = np.mean(weeks, axis=1)

print("\nWeekly Averages:")
for i, avg in enumerate(weekly_averages, 1):
    print(f"Week {i}: {avg:.2f}°C")

# If you want to include the last two days as a partial week:
last_week_avg = np.mean(daily_temperatures[28:])
print(f"\nAverage for the last 2 days: {last_week_avg:.2f}°C")

Daily Temperatures for the Month:
[38 29 29 32 23 32 39 38 20 35 38 32 38 38 35 34 26 39 24 27 36 24 26 33
 34 34 36 35 30 35]

Weekly Averages:
Week 1: 31.71°C
Week 2: 34.14°C
Week 3: 31.57°C
Week 4: 31.71°C

Average for the last 2 days: 32.50°C
